#!/usr/bin/env bash
# Displays numbers from 1 to 20 in addition to:
#   "bad luck from Kenya" for the 4th iteration
#   "bad luck from Tanzania" for the 9th iteration
#   "bad luck from Uganda" for the 17th loop iteration

count=1

while [ $count -le 20 ]
do
  echo "$count"
  case $count in
    "4") echo "bad luck from Kenya";;
    "9") echo "bad luck from Tanzania";;
    "17") echo "bad luck from Uganda";;
  esac
  (( count++ ))
done
